#IFPB - Engenharia de computação
##Aluno: Rafael Victor C. Muniz - 7°P

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
nullVector = np.zeros(10)
print(nullVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
array1 = np.array([9, 50, 10, 13])
# Tamanho da memória do numpy array em bytes
print(array1.size * array1.itemsize)

32


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
nullVector = np.zeros(10)
nullVector[4] = 1
nullVector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vector = np.arange(10)
print("Antes:", vector)
vector = np.flip(vector)
print("Depois:", vector)

Antes: [0 1 2 3 4 5 6 7 8 9]
Depois: [9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matriz = np.arange(9).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
print(np.random.random((3, 3, 3)))

[[[0.75492899 0.08927393 0.42280882]
  [0.28261838 0.10428875 0.85444165]
  [0.13377053 0.30177853 0.14115046]]

 [[0.98529345 0.90934031 0.44353142]
  [0.98060425 0.2686837  0.52610687]
  [0.30883206 0.00683656 0.85019116]]

 [[0.61432061 0.52347796 0.95111606]
  [0.11988467 0.56839726 0.56818266]
  [0.55010804 0.27446862 0.51240431]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
array = np.random.random((10,10))
arrayMin, arrayMax = array.min(), array.max()
print(array)
print(arrayMin)
print(arrayMax)

[[7.89614201e-01 8.83599247e-01 7.36707056e-01 6.24553457e-01
  3.93714632e-01 3.04667121e-01 5.82153653e-01 9.21839729e-01
  6.57088547e-02 6.82603025e-01]
 [9.34870737e-01 6.44254807e-01 8.75695470e-02 6.83385736e-01
  6.08899855e-01 5.93733809e-01 3.10213307e-01 7.12938413e-01
  2.08629042e-01 9.68669749e-01]
 [7.11954746e-02 5.67190619e-01 1.69683400e-01 8.76756184e-01
  5.89083848e-01 5.02052585e-01 8.40076741e-01 5.23143742e-01
  2.92740299e-01 4.99203190e-01]
 [7.89627314e-01 7.13761887e-01 2.52679059e-01 9.02538441e-01
  1.13968304e-01 8.06883425e-01 2.11128102e-01 3.21462317e-01
  8.41170503e-01 4.97274547e-01]
 [2.15085877e-02 1.26944152e-01 9.10188033e-01 8.31335331e-01
  9.85179418e-01 6.83917433e-01 1.40045874e-02 1.59366177e-01
  2.10136369e-01 3.14329860e-01]
 [6.45096913e-01 3.48370472e-01 4.97838218e-01 1.99195078e-01
  9.23805515e-01 1.22332197e-01 6.51503374e-02 5.57911053e-01
  6.54224249e-01 4.70736570e-01]
 [6.74983895e-01 3.74143913e-01 9.21990977e-01 9.73445923e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
array = np.random.random(100)
array.sort()
print(array)
print(array.mean())

[7.70531001e-04 2.81354477e-02 3.29500740e-02 4.07045643e-02
 5.65626606e-02 6.60249046e-02 6.62546863e-02 6.72803565e-02
 7.34378218e-02 7.45905437e-02 8.34068219e-02 8.63687374e-02
 8.98657487e-02 9.29359980e-02 1.02114152e-01 1.11372647e-01
 1.13432234e-01 1.15631055e-01 1.23501477e-01 1.33034255e-01
 1.35859567e-01 1.37130346e-01 1.38895115e-01 1.55650995e-01
 1.68063670e-01 1.68411305e-01 2.11293268e-01 2.20066309e-01
 2.42033603e-01 2.46288248e-01 2.47194467e-01 2.68719595e-01
 2.74014229e-01 2.96317962e-01 2.99655524e-01 3.04704579e-01
 3.22365374e-01 3.28229013e-01 3.32124406e-01 3.46940995e-01
 3.49244540e-01 3.55623215e-01 3.70513362e-01 3.75261911e-01
 4.37466517e-01 4.45718082e-01 4.51992406e-01 4.76724765e-01
 4.89391808e-01 4.92503655e-01 5.21968389e-01 5.24512114e-01
 5.24987033e-01 5.35365279e-01 5.45280185e-01 5.51932306e-01
 5.57926164e-01 5.59622726e-01 5.68033343e-01 5.68231783e-01
 5.90607844e-01 6.22269766e-01 6.22462749e-01 6.62628681e-01
 6.75814246e-01 6.767261

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
array = np.ones((5,5))
print("Antes:\n", array)
array[1:-1,1:-1] = 0
print("Depois:\n", array)

Antes:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Depois:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
array = np.arange(25).reshape(5,5)
print("Antes:\n", array)
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Depois:\n", array)

Antes:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Depois:
 [[ 0  0  0  0  0  0  0]
 [ 0  0  1  2  3  4  0]
 [ 0  5  6  7  8  9  0]
 [ 0 10 11 12 13 14  0]
 [ 0 15 16 17 18 19  0]
 [ 0 20 21 22 23 24  0]
 [ 0  0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
array = np.diag([1, 2, 3, 4, 5])
print(array)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
array = np.ones((3,3))
array = np.zeros((8,8),dtype=int)
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
array = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
array = np.random.random((5,5))
array = (array - np.mean (array)) / (np.std (array))
print(array)

[[ 1.00509192 -1.17132683  1.59243846  1.40103109 -1.5391085 ]
 [ 1.63473157 -0.30232846 -1.23668403  0.65155789 -0.79005079]
 [ 0.37343521  0.75927353 -0.60110255 -1.59399771 -0.35582674]
 [-1.24893273 -1.13235627  0.68739331 -0.10873801  0.18138847]
 [ 0.53288778 -0.88360978  0.03307258  0.98983201  1.12192855]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
array = np.dot(np.ones((5,3)), np.ones((3,2)))
print(array)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
array = np.arange(11)
array[(3 < array) & (array < 8)] *= -1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
# Vetor de inteiros
Z = [1,2,3]

In [28]:
try:
  print("Operação legal! Resultado = {}".format(Z**Z))
except:
  print("Operação ilegal!")

Operação ilegal!


In [29]:
try:
  print("Operação legal! Resultado = {}".format(2 << Z >> 2))
except:
  print("Operação ilegal!")

Operação ilegal!


In [30]:
try:
  print("Operação legal! Resultado = {}".format(Z <- Z))
except:
  print("Operação ilegal!")

Operação ilegal!


In [31]:
try:
  print("Operação legal! Resultado = {}".format(1j*Z))
except:
  print("Operação ilegal!")

Operação ilegal!


In [32]:
try:
  print("Operação legal! Resultado = {}".format(Z/1/1))
except:
  print("Operação ilegal!")

Operação ilegal!


In [33]:
try:
  print("Operação legal! Resultado = {}".format(Z<Z>Z))
except:
  print("Operação ilegal!")

Operação legal! Resultado = False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [34]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [35]:
array = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(array)), array))

[ -6.  -9. -10.  -2.  -5.  -8.   2.   6.   5.   9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [36]:
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)
print(np.intersect1d(array1,array2))

[2 4 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [37]:
defaults = np.seterr(all="ignore")
X = np.ones(1) / 0

In [38]:
# Voltando para configuração padrão
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [39]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
#False

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [40]:
ontem = np.datetime64('today') - np.timedelta64(1)
hoje = np.datetime64('today')
amanha = np.datetime64('today') + np.timedelta64(1)

print(ontem)
print(hoje)
print(amanha)

2022-09-29
2022-09-30
2022-10-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [41]:
array = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(array)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [42]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [43]:
array = np.random.uniform(0,10,10)
print("Array inicial:")
print(array, "\n")
print(array - array%1)
print(array // 1)
print(np.floor(array))
print(array.astype(int))
print(np.trunc(array))

Array inicial:
[5.93854394 3.27924615 4.80215341 0.40333328 3.59506293 9.64176335
 6.90758995 9.23201844 7.44239609 7.04026873] 

[5. 3. 4. 0. 3. 9. 6. 9. 7. 7.]
[5. 3. 4. 0. 3. 9. 6. 9. 7. 7.]
[5. 3. 4. 0. 3. 9. 6. 9. 7. 7.]
[5 3 4 0 3 9 6 9 7 7]
[5. 3. 4. 0. 3. 9. 6. 9. 7. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [44]:
array = np.zeros((5,5))
array += np.arange(5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [45]:
def generator():
  aux = []
  for i in range(10):
    aux.append(i)
  return aux

array = generator()
print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [46]:
array = np.linspace(0,1,11,endpoint=False)[1:]
print(array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [47]:
array = np.random.random(10)
array.sort()
print(array)

[0.14947264 0.22474826 0.25265816 0.31135932 0.52867095 0.60799305
 0.64662963 0.72193069 0.75070881 0.94180871]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [48]:
array = np.arange(10)
np.add.reduce(array)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [49]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

A = [1,2,3,4]
B = [1,2,3,4]

equal = np.array_equal(A,B)
print(equal)

False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [50]:
array = np.zeros(10)
array.flags.writeable = False

# Teste se é mutável
try:
  array[0] = 1
except:
  print("Operação não permitida!")

Operação não permitida!


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [51]:
array = np.random.random((10,2))
x = array[:,0]
y = array[:,1]

r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.74568655 0.21338118 0.86730023 0.61139896 0.13888475 1.21632067
 0.81390036 0.73233288 0.95012594 0.95063777]
[0.33144537 0.07589447 1.26450414 1.06586738 0.29935447 0.73857458
 0.74258862 0.83465576 0.66274815 0.51595318]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [52]:
array = np.random.random(10)
array[array.argmax()] = 0
print(array)

[0.45110185 0.93475471 0.31793514 0.         0.15702085 0.04445912
 0.30527648 0.6124114  0.35932009 0.0547797 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [53]:
array = np.zeros((5,5), [('x',float),('y',float)])
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [54]:
array = np.arange(8)
X = array + 0.5
Y = 1.0 / np.subtract.outer(array, X)
print(np.linalg.det(Y))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [55]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [56]:
np.set_printoptions(threshold=float("inf"))
array = np.zeros((40,40))
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [57]:
array = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(array-v)).argmin()
print(array[index])

59


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [58]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]),
                   ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [59]:
array = np.random.random((10,2))
X, Y = np.atleast_2d(array[:,0], array[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.37083361 0.45220707 0.29048454 0.91915794 0.91227396
  0.7242682  0.79989938 0.87672683 0.87829565]
 [0.37083361 0.         0.12050793 0.65991691 0.850573   1.1032111
  0.96459718 0.9679694  0.78728283 0.88332759]
 [0.45220707 0.12050793 0.         0.73197136 0.75838081 1.07958498
  0.96237436 0.94023061 0.69178763 0.80912575]
 [0.29048454 0.65991691 0.73197136 0.         1.03231143 0.81242048
  0.5940126  0.73601502 1.00776488 0.94353621]
 [0.91915794 0.850573   0.75838081 1.03231143 0.         0.68252784
  0.74503443 0.56989977 0.07321097 0.17593179]
 [0.91227396 1.1032111  1.07958498 0.81242048 0.68252784 0.
  0.22355287 0.14207049 0.72221716 0.50705927]
 [0.7242682  0.96459718 0.96237436 0.5940126  0.74503443 0.22355287
  0.         0.2048245  0.7648013  0.58405278]
 [0.79989938 0.9679694  0.94023061 0.73601502 0.56989977 0.14207049
  0.2048245  0.         0.60152846 0.39908402]
 [0.87672683 0.78728283 0.69178763 1.00776488 0.07321097 0.72221716
  0.7648013  0.601528

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [60]:
arrayFloat = (np.random.rand(10)*100).astype(np.float32)
x = arrayFloat.view(np.int32)
x[:] = arrayFloat
print(x)

[ 4 75 37  5 92 78 15 36 71 31]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [61]:
array = np.arange(9).reshape(3,3)

print("enumerate:")
for index, value in np.ndenumerate(array):
    print(index, value)

print("equivalent:")
for index in np.ndindex(array.shape):
    print(index, array[index])

enumerate:
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
equivalent:
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [62]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
R = np.sqrt(X*X+Y*Y)
sigma = 1.0
mu = 0.0
Z = np.exp(-((R-mu)**2/(2.0*sigma**2)))
print(Z)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [63]:
size = 8
replacedElements = 6
array = np.zeros((size,size))
np.put(array, np.random.choice(range(size*size), replacedElements, replace=False),1)
print(array)

[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [64]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.23584649  0.17665506  0.42582492  0.39138968 -0.07322095 -0.14319222
  -0.20267131 -0.40707803 -0.29063688  0.35877623]
 [ 0.47780223 -0.0683674  -0.39029731  0.16723626 -0.02417323  0.32181571
  -0.1133714  -0.15608291  0.0208955  -0.23545746]
 [ 0.06443501 -0.29346667 -0.09927242  0.27594364 -0.02393083  0.39470092
  -0.5133966  -0.12134787 -0.0699431   0.38627792]
 [ 0.03081614 -0.18502915  0.32932401 -0.50037769 -0.47700137  0.36160696
   0.44917226  0.12516821 -0.26651209  0.13283273]
 [ 0.07041521 -0.31220258  0.4716896   0.0129779  -0.45725354  0.02157393
   0.02329788  0.07497666  0.48453877 -0.39001382]]


#### 59. How to sort an array by the nth column? (★★☆)

In [65]:
array = np.random.randint(0,10,(3,3))
print(array)
print(array[array[:,1].argsort()])

[[9 9 4]
 [1 0 2]
 [2 7 4]]
[[1 0 2]
 [2 7 4]
 [9 9 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [66]:
array = np.random.randint(0,3,(3,10))
print((~array.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [67]:
array = np.random.uniform(0,1,10)
value = 0.5
result = array.flat[np.abs(array - value).argmin()]
print(result)

0.4631281997134653


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [68]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [69]:
class arrayName(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

In [70]:
array = arrayName(np.arange(10), "class")
print (array.name)

class


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [71]:
array = np.ones(10)
n = np.random.randint(0,len(array),20)
array += np.bincount(n, minlength=len(array))
print(array)

[2. 2. 2. 3. 2. 5. 3. 4. 3. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [72]:
X = [2,3,4,5,6,7]
I = [1,8,6,2,4,1]
F = np.bincount(I,X)
print(F)

[0. 9. 5. 0. 6. 0. 4. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [73]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [74]:
array = np.random.randint(0,10,(3,4,3,4))
sum = array.sum(axis=(-2,-1))
print(sum)

[[41 68 54 61]
 [43 73 61 44]
 [47 48 59 60]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [75]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(pd.Series(D).groupby(S).mean())

0    0.587275
1    0.372821
2    0.423728
3    0.622936
4    0.545596
5    0.340865
6    0.630463
7    0.370455
8    0.479404
9    0.625250
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [76]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([0.82828802, 1.61224676, 1.30381306, 1.54702497, 0.54911926])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [77]:
array = np.array([1,2,3,4,5])
narray = 3
array0 = np.zeros(len(array) + (len(array)-1)*(narray))
array0[::narray+1] = array
print(array0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [78]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [79]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [80]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 26) ( 3, 74) ( 5, 23) ( 5, 69) (10, 22) (10, 89) (14, 24) (14, 91)
 (18, 32) (18, 52) (18, 81) (18, 99) (22, 89) (23, 69) (24, 91) (26, 74)
 (29, 48) (29, 84) (32, 52) (33, 67) (33, 84) (36, 44) (36, 90) (44, 90)
 (48, 84) (57, 66) (57, 97) (66, 97) (67, 84) (81, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [81]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [82]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [83]:
array = np.arange(10)
print(sliding_window_view(array, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [84]:
array = np.random.randint(0,2,100)
np.logical_not(array, out=array)

array = np.random.uniform(-1.0,1.0,100)
np.negative(array, out=array)

array([-0.5787088 ,  0.92417273,  0.03641612,  0.87178979, -0.84141666,
       -0.84954753,  0.02731071,  0.21952343, -0.46268662,  0.22446243,
        0.43412958,  0.97032613,  0.41834019,  0.58168135, -0.51785713,
        0.93562428,  0.64956891, -0.72728829, -0.52853811,  0.79478058,
       -0.0839051 ,  0.81827012, -0.49449042, -0.80678877,  0.73827937,
       -0.31396319,  0.17919458, -0.59193035,  0.08691612,  0.73333642,
        0.35446795, -0.84580702, -0.65066238, -0.47196241, -0.20291989,
       -0.02432275, -0.79954369, -0.269183  , -0.00653544,  0.89824966,
        0.93419189,  0.43777917, -0.06285535, -0.89988286,  0.65290022,
        0.16276671, -0.17915773,  0.96468872,  0.94481892, -0.42626911,
       -0.25048224, -0.36667388,  0.75111005,  0.59145386,  0.06395944,
       -0.17720809, -0.52104472,  0.08560677, -0.72593402,  0.56225223,
        0.23651468,  0.8709418 ,  0.63758553,  0.13661586,  0.69825448,
        0.71458602,  0.4119125 ,  0.66080438,  0.14613335, -0.11

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [85]:
array = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(array, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [86]:
array = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(array)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [87]:
array = np.random.randint(0,10,50)
print(np.bincount(array).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [88]:
array = np.random.randint(0,5,(10,10))
print(sliding_window_view(array, window_shape=(3, 3)))

[[[[1 4 2]
   [1 4 4]
   [2 0 4]]

  [[4 2 2]
   [4 4 4]
   [0 4 2]]

  [[2 2 0]
   [4 4 2]
   [4 2 1]]

  [[2 0 4]
   [4 2 3]
   [2 1 2]]

  [[0 4 2]
   [2 3 4]
   [1 2 4]]

  [[4 2 2]
   [3 4 1]
   [2 4 4]]

  [[2 2 2]
   [4 1 2]
   [4 4 2]]

  [[2 2 3]
   [1 2 1]
   [4 2 1]]]


 [[[1 4 4]
   [2 0 4]
   [1 3 2]]

  [[4 4 4]
   [0 4 2]
   [3 2 0]]

  [[4 4 2]
   [4 2 1]
   [2 0 4]]

  [[4 2 3]
   [2 1 2]
   [0 4 0]]

  [[2 3 4]
   [1 2 4]
   [4 0 3]]

  [[3 4 1]
   [2 4 4]
   [0 3 4]]

  [[4 1 2]
   [4 4 2]
   [3 4 1]]

  [[1 2 1]
   [4 2 1]
   [4 1 3]]]


 [[[2 0 4]
   [1 3 2]
   [0 4 1]]

  [[0 4 2]
   [3 2 0]
   [4 1 1]]

  [[4 2 1]
   [2 0 4]
   [1 1 0]]

  [[2 1 2]
   [0 4 0]
   [1 0 2]]

  [[1 2 4]
   [4 0 3]
   [0 2 4]]

  [[2 4 4]
   [0 3 4]
   [2 4 3]]

  [[4 4 2]
   [3 4 1]
   [4 3 1]]

  [[4 2 1]
   [4 1 3]
   [3 1 0]]]


 [[[1 3 2]
   [0 4 1]
   [4 1 4]]

  [[3 2 0]
   [4 1 1]
   [1 4 0]]

  [[2 0 4]
   [1 1 0]
   [4 0 3]]

  [[0 4 0]
   [1 0 2]
   [0 3 3]]

  [[4 0 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [89]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [90]:
array = np.ones((16,16))
k = 4
result = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], k), axis=0),
                                       np.arange(0, array.shape[1], k), axis=1)
print(result)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [91]:
array = np.arange(10000)
np.random.shuffle(array)
n = 5

print(array[np.argsort(array)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [92]:
array = np.array([("Cadeira", 4.9, 10),
              ("PC", 3.4, 7)])
array2 = np.core.records.fromarrays(array.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(array2)

[(b'Cadeira', 4.9, 10) (b'PC', 3.4,  7)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [93]:
Z = np.random.rand(int(5e7))

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

4.36 s ± 1.28 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
139 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
119 ms ± 1.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [94]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [95]:
array = np.random.randint(0,5,(10,3))
print(array, "\n")
X = np.all(array[:,1:] == array[:,:-1], axis=1)
result = array[~X]
print(result)

[[1 4 1]
 [0 3 3]
 [3 4 1]
 [0 2 2]
 [3 2 3]
 [0 2 2]
 [4 3 1]
 [1 4 2]
 [0 4 1]
 [3 4 4]] 

[[1 4 1]
 [0 3 3]
 [3 4 1]
 [0 2 2]
 [3 2 3]
 [0 2 2]
 [4 3 1]
 [1 4 2]
 [0 4 1]
 [3 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [96]:
vectorInts = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
matrix = ((vectorInts.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(matrix[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [97]:
array = np.random.randint(0,2,(6,3))
rasult = np.unique(array, axis=0)
print(rasult)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [98]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)     
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)   

array([[0.45736916, 0.19776852, 0.78367803, 0.11235543, 0.61017937,
        0.86765945, 0.32616401, 0.16343139, 0.42731289, 0.31730877],
       [0.35105663, 0.1517985 , 0.60151709, 0.08623913, 0.46834708,
        0.66597757, 0.25034927, 0.12544281, 0.32798675, 0.24355238],
       [0.19473651, 0.08420496, 0.33367078, 0.04783817, 0.25979933,
        0.369428  , 0.13887259, 0.06958506, 0.18193929, 0.13510225],
       [0.21554361, 0.09320204, 0.36932265, 0.05294956, 0.28755822,
        0.40890043, 0.15371077, 0.07702004, 0.20137904, 0.14953758],
       [0.40342329, 0.17444208, 0.69124462, 0.09910331, 0.53820981,
        0.76532058, 0.28769355, 0.14415496, 0.37691211, 0.27988277],
       [0.4563218 , 0.19731564, 0.78188344, 0.11209814, 0.60878208,
        0.86567254, 0.32541711, 0.16305714, 0.42633436, 0.31658214],
       [0.06320259, 0.02732909, 0.10829433, 0.01552609, 0.08431902,
        0.11989949, 0.04507171, 0.02258414, 0.0590492 , 0.04384803],
       [0.35687732, 0.15431539, 0.6114905

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [99]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [100]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [101]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.10202287  0.25714246]
